### ISSUE TITLE
The first condition should be d (I mean x value in the formula) used instead of the ascendant value found

### ISSUE THREAD

**Issue by Augustpi** [0xStarcat/CircularNatalHoroscopeJS#1]
https://github.com/0xStarcat/CircularNatalHoroscopeJS/blob/c65e40d9b901b1143ca14af831e05de9ae004835/src/utilities/astronomy.js#L112

The first condition should be x < 0 (I mean d value),
The x (d) value in the formula should be used instead of the ascendant value found in the first condition.

- The Ascendant is then found in the correct quadrant (0 to 360 degrees) by using the two rules
https://wikimedia.org/api/rest_v1/media/math/render/svg/68649ded47b9e668ef643fbf313d157ed4037022

![image](https://user-images.githubusercontent.com/4258004/90976292-7d3e6780-e544-11ea-97d2-3eae0fef8cbe.png)

`  const b = sinFromDegrees(obliquityEcliptic) * tanFromDegrees(latitude)`
`  const c = cosFromDegrees(obliquityEcliptic) * sinFromDegrees(localSiderealTime)`
`  const d = b + c`

Line `  if (d < 0) { ...`

So, I've tried a lot and it's true that way (of course it still needs verification)

thanks a lot
Onur

**Comment by 0xStarcat** [comment]
Resolved by #2
