### ISSUE TITLE
Degrees are a bit off

### ISSUE THREAD

**Issue by hjimenez** [0xStarcat/CircularNatalHoroscopeJS#11]
Hello, thanks for such a great library! I did a calculation on several charts and I see the moon is offset by 3 degrees. Tried with the different house systems. 
-For 7/7/1973 20:30 at 25.6866142, -100.3161126, Moon is at 24 degrees and with there library I get 21 degrees. 
-For 10/31/1970 16:20 at 32.5149469, -117.0382471,  Moon is at 28 degrees but with library I get 24 degrees.

Maybe I am doing something incorrect?

**Comment by 0xStarcat** [comment]
I can confirm this issue. I'll look into it and make an update to https://github.com/0xStarcat/Moshier-Ephemeris-JS . That repo is where the astronomy calculations are handled.

**Comment by 0xStarcat** [comment]
Fix applied with https://github.com/0xStarcat/CircularNatalHoroscopeJS/pull/12

and released in `v1.0.12` https://github.com/0xStarcat/CircularNatalHoroscopeJS/releases/tag/v1.0.12

Thank you for performing these tests and catching the issue!
