### ISSUE TITLE
Import using require

### ISSUE THREAD

**Issue by NikolaGrujic91** [0xStarcat/CircularNatalHoroscopeJS#15]
Hi, 

In the Readme.md it is advised to import library in this fashion:

`import { Origin, Horoscope } from "circular-natal-horoscope-js";`

Is it possible to import library using require? Is there some workaround how this can be accomplished?

`const { Origin, Horoscope } = require('circular-natal-horoscope-js');`

Kind regards,
Nikola

**Comment by 0xStarcat** [comment]
yes! As far as I can tell (did a quick test with a starter template) using `require` like you proposed works just fine.
