### ISSUE TITLE
Readme suggestion

### ISSUE THREAD

**Issue by NikolaGrujic91** [0xStarcat/CircularNatalHoroscopeJS#16]
Please add to the Readme.md instructions how to add library to dependencies in package.json.

**Comment by 0xStarcat** [comment]
good idea :+1:

**Comment by NikolaGrujic91** [comment]
Thank you for answering on all issues. I hope I did not spam you too much.

Thank you for making this great library !

Cheers :)

**Comment by 0xStarcat** [comment]
No problem! I added some notes into the new release `1.0.14` from #18 

Let me know if this is sufficient: https://github.com/0xStarcat/CircularNatalHoroscopeJS#installation

Feel free to add any suggestions! I'll close this issue in a day or so

**Comment by NikolaGrujic91** [comment]
Looks good 👍

**Comment by 0xStarcat** [comment]
Thanks! :)
