### ISSUE TITLE
Juno position 

### ISSUE THREAD

**Issue by NikolaGrujic91** [0xStarcat/CircularNatalHoroscopeJS#17]
Hi,

Is it possible to calculate sign for the Juno asteroid?

Kind regards,
Nikola

**Comment by 0xStarcat** [comment]
At this time, no. However, this should be possible by updating a separate repo (which I'm also maintaining).

I haven't found the time yet to look up how to add more bodies like asteroids to the ephemeris dependency but I've added this issue to the list in the repo (under Issues)

https://github.com/0xStarcat/Moshier-Ephemeris-JS/

see this file:
https://github.com/0xStarcat/Moshier-Ephemeris-JS/blob/master/src/constants/celestialBodies.js
