### ISSUE TITLE
other repository/plugin for astrochart

### ISSUE THREAD

**Issue by seetpalsingh** [0xStarcat/CircularNatalHoroscopeJS#22]
Hi, I saw you are using other plugin to draw the graph.
i found that plugin here https://www.npmjs.com/package/astrochart but. not much documentation.

are you using the same plugin or its different?

because, i need to implement that astrology chart ,zodiac  and other things.

i have confusion of that chart draw thing.

please, provide some more details on that chart draw.

**Comment by 0xStarcat** [comment]
hello! The demo I provide in this library uses a different package to display the chart. More information (and examples) can be found in this repo https://github.com/Kibo/AstroChart . The link you provided seems to be a different package (same name, different author) You can also view my implementation in the demo script https://github.com/0xStarcat/CircularNatalHoroscopeJS/blob/master/demo/script.js

hope this helps! let me know if you have any other questions about it
