### ISSUE TITLE
circularNatalHoroscopeJs data related to AstroChartJS

### ISSUE THREAD

**Issue by seetpalsingh** [0xStarcat/CircularNatalHoroscopeJS#23]
Hi,

I tried to get the data from your plugin required by astroChart.

AstroChart working with:

 var data = {
				"planets":{
            "Lilith":[18], 
            "Chiron":[18], 
            "Pluto":[63], 
            "Neptune":[110, 0.2], 
            "Uranus":[318], 
            "Saturn":[201, -0.2], 
            "Jupiter":[192], 
            "Mars":[210], 
            "Moon":[268], 
            "Sun":[281], 
            "Mercury":[312], 
            "Venus":[330], 
            "NNode":[2]
          },
				"cusps":[296, 350, 30, 56, 75, 94, 116, 170, 210, 236, 255, 274]			
			};

but, but getting totally different data from your plugin, like:

"Ephemeris":{
      "_calculateMotion":true,
      "_calcHeliocentricLongitudesOnly":false,
      "_calculateShadows":false,
      "_moonQuarterApproximationValue":1.5,
      "Observer":{
         "year":2020,
         "month":11,
         "day":1,
         "hours":21,
         "minutes":30,
         "seconds":0,
         "latitude":40,
         "longitude":-70,
         "height":0,
         "glat":40,
         "tlong":-70,
         "attemp":12,
         "atpress":1010,
         "trho":0.9986215196058488,
         "tlat":39.810610550934875,
         "Date":{
            "utc":"2020-12-01T21:30:00.000Z",
            "dateString":"Wed Dec 02 2020",
            "julian":2459185.3958333335,
            "j2000":2020.918263746293,
            "b1950":2020.9184745608036,
            "j1900":2020.918263746293,
            "universalJulian":2459185.395005166,
            "universalDate":"2020-12-01T21:28:48.446Z"
         }
      },
      "Earth":{
         "_body":{
            "key":"earth",
            "type":"heliocentric",
            "anomaly":1.1791,
            "dailyMotion":0.985611,
            "distance":0,
            "eccentricity":0.016713,
            "epoch":2446800.5,
            "equinox":2446800,
            "inclination":0,
            "longitude":0,
            "magnitude":-3.86,
            "node":0,
            "perihelion":102.884,
            "perturbation":0,
            "ptable":{
               "maxargs":12,
               "max_harmonic":[],
               "max_power_of_t":3,
               "distance":1.000139872959708,
               "timescale":3652500,
               "trunclvl":0.0001,
               "lon_tbl":[],
               "lat_tbl":[],
               "rad_tbl":[],
               "arg_tbl":[]
            },
            "semiAxis":0.999999,
            "semiDiameter":0
         },
         "_key":"earth",
         "locals":{
            "dp":[
               
            ],
            "dradt":null,
            "ddecdt":null,
            "EO":0,
            "SE":0,
            "SO":0,
            "pq":0,
            "ep":0,
            "qe":0
         },
         "aberration":{
            
         },
         "lightTime":{
            
         },
         "position":{
            "rect":[
               0.3392690733836876,
               0.8493064484820125,
               0.36817062811800944
            ],
            "polar":[
               1.2194891127571037,
               -0.000045206773486035605,
               0.9858877010068464
            ]
         },
         "distance":0.9859186532079337,
         "epoch":2459185.3958333335,
         "semiAxis":0.999999,
         "semiDiameter":0,
         "key":"earth",
         "type":"heliocentric",
         "anomaly":1.1791,
         "dailyMotion":0.985611,
         "eccentricity":0.016713,
         "equinox":2446800,
         "inclination":0,
         "longitude":0,
         "magnitude":-3.86,
         "node":0,
         "perihelion":102.884,
         "perturbation":0,
         "ptable":{}
      },

Can you please provide some guidance

**Comment by GitAttila** [comment]
It is not right to expect that the output of this CircularNatalHoroscope would match exactly some AstroChart plugin. A developer should be ready to remap the output object and tweak it into what is needed. Today it is some AstroChart tomorrow it is another, they will both have different input requirements.

**Comment by 0xStarcat** [comment]
Please refer to [this section of the documentation](https://github.com/0xStarcat/CircularNatalHoroscopeJS#implementation--use)  (number #3) and [this section](https://github.com/0xStarcat/CircularNatalHoroscopeJS#interpreting-chartpositions) (chart positions). The data object this library provides is more complicated then what AstroChart gives, but all of the values you need are in there. 

If you need the house cusps, you'll need to traverse the data object like so: `<ephemeris>.Houses` to get an Array of houses. Each house will give you the degrees with `<House>.ChartPosition.StartPosition.Ecliptic.DecimalDegrees`

If you need the zodiac cusps, it's `<ephemeris>.ZodiacCusps` to get an array of zodiac cusps, and each cusp will give you the degrees with `<ZodiacCusp>`.ChartPosition.Ecliptic.DecimalDegrees` 

For bodies (sun, moon, mercury, etc), its `<ephemeris>.CelestialBodies` which gives you an object with keys for each body. Each body also has a `ChartPosition`. 

Same with Ascendant, Midheaven, etc.

Let me know if you have any more questions! Will close for now but happy to keep discussing.

**Comment by mexantco** [comment]
hi, how can I define retrograde using your script?

**Comment by 0xStarcat** [comment]
Hi, 

for retrograde, have a look at [this code from the demo script](https://github.com/0xStarcat/CircularNatalHoroscopeJS/blob/master/demo/script.js#L266-L281). Each result from `horoscope.CelestialBodies.all` has a `isRetrograde` function which returns true / false. 

This function checks the value of `dailyMotion` - if its positive, it's moving forward. if it's negative, it's retrograde.
