### ISSUE TITLE
(SOLVED) - Possible bug with position of Planet in House

### ISSUE THREAD

**Issue by marciliosoulloop** [0xStarcat/CircularNatalHoroscopeJS#26]
Hi! First of all, thank you for this great library!

We found a possible divergence in the position of some planets when using the Horoscope object. We compared the result with Vega software and others, with the same data and home system.

This is the object with birth data.

`const origin = new Origin({
      year: 1997,
      month: 11, // 0 = January, 11 = December!
      date: 20,
      hour: 0,
      minute: 20,
      latitude: 23.3251,
      longitude: -46.3810,
    });`

This is the call for Horoscope object with proper parameters.

`const horoscope = new Horoscope({
      origin: originCarol,
      houseSystem: 'placidus',
      zodiac: 'tropical',
      aspectPoints: ['bodies', 'points', 'angles'],
      aspectWithPoints: ['bodies', 'points', 'angles',],
      aspectTypes: ['major', 'minor'],
      customOrbs: {},
      language: 'en',
    });`

This is the result from CircularnatalhoroscopeJs:

![image](https://user-images.githubusercontent.com/77651274/138618357-1f575875-49a6-4e7f-9739-ad77b35ff69b.png)

And following is the result from other software that we are sure that is correct.

![image](https://user-images.githubusercontent.com/77651274/138618605-10e6bdc3-9b2a-4ed4-aeeb-47f0c3961978.png)

Please, notice that Neptune has the same degrees on both images but your lib says that this planet is on House 4 and the correct is house 5.
Also Mars have a small diference in the seconds and different houses. The correct is house 5.

Please, can you tell me if I'm doing anything wrong?
Thank you!

**Comment by marciliosoulloop** [comment]
Problem was on wrong latitude and longitude.

**Comment by marciliosoulloop** [comment]
Problem was on wrong latitude and longitude.

**Comment by 0xStarcat** [comment]
Hello! sorry for the late reply - had a busy couple of weeks. I'm glad you were able to resolve it :) 

Also very glad to hear the results are matching up with other software.
