### ISSUE TITLE
Drawing into SVG

### ISSUE THREAD

**Issue by j** [0xStarcat/CircularNatalHoroscopeJS#4]
Any time frame on when you think you'll successfully draw this into SVG or know how to exactly tackle it for 3rd party attempts?

**Comment by 0xStarcat** [comment]
Hello! sorry for the late reply. There's no plans for this repository to actually perform any of the rendering or SVG work, but only for it to act as the calculation library for other libraries to use when doing their own rendering. This repo is intended to be a modular library used in conjunction with others and not strictly for rendering. 

I used this one for testing out some of the rendering on my own and it's pretty good https://github.com/Kibo/AstroChart

**Comment by 0xStarcat** [comment]
If you use this library with any rendering work of your own or find other good libraries as examples, I'd love to link to them in the readme!
