### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by aintHuman** [0xStarcat/CircularNatalHoroscopeJS#5]
What library do you recommend for rendering natal chart using data generated by this package, for React?

**Comment by 0xStarcat** [comment]
I don't know of any React-specific libraries for rendering the chart - I only came across a couple of libraries which do rendering-only work like this one: https://github.com/Kibo/AstroChart and I didn't find any react-specific ones. If you do, I'd love to link to it in the README!

**Comment by aintHuman** [comment]
Thanks I have been using AstroChart. Its quite good.
