### ISSUE TITLE
Support for Typescript/Angular

### ISSUE THREAD

**Issue by GitAttila** [0xStarcat/CircularNatalHoroscopeJS#7]
It would be really helpful to add functionality for typescript. I was unable to use this inside of Angular:

Could not find a declaration file for module 'circular-natal-horoscope-js'. '/Users/.../astro-chart/node_modules/circular-natal-horoscope-js/dist/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/circular-natal-horoscope-js` if it exists or add a new declaration (.d.ts) file containing `declare module 'circular-natal-horoscope-js';`

**Comment by 0xStarcat** [comment]
agreed - typescript would be a great feature to add. you might have more experience with typescript than me - is there any chance you can help w/ a PR? otherwise I'll look into it this upcoming week / weekend

**Comment by 0xStarcat** [comment]
Apologies - got a bit busy. this won't be a high priority for me at the moment so if you or anyone wants to submit a PR adding typescript support and a `.d.ts` file then please do - it'll be greatly appreciated.

**Comment by 0xStarcat** [comment]
I'm going to be following this: https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html

**Comment by 0xStarcat** [comment]
@GitAttila would you mind giving this a PR review? Could you test and see if this solves your issues in your angular project? https://github.com/0xStarcat/CircularNatalHoroscopeJS/pull/9

**Comment by 0xStarcat** [comment]
This should now be fixed by https://github.com/0xStarcat/CircularNatalHoroscopeJS/pull/13

and released in `v1.0.13` https://github.com/0xStarcat/CircularNatalHoroscopeJS/releases/tag/v1.0.13 

I tested it myself in a typescript Angular app and had no issues. 

Thanks for raising this issue and helping to adopt wider support in Typescript projects!
