### ISSUE TITLE
Add new bodies

### ISSUE THREAD

**Issue by aintHuman** [0xStarcat/CircularNatalHoroscopeJS#8]
Is it possible to add bodies which are not included by default?

For instance, 'Ceres'.

I presume you are using the Swiss ephemeris, in which case, is it possible to add custom objects defined by the body code?

**Comment by 0xStarcat** [comment]
This repo is using another library I worked on which is a fork from an original implementation - Moshier Ephemeris JS https://github.com/0xStarcat/Moshier-Ephemeris-JS

I haven't added any new bodies yet but from what I can see you might be able to add Ceres if you can fill out it's `pTable` https://github.com/0xStarcat/Moshier-Ephemeris-JS/tree/master/src/ptables . 

A PR in that repo would be welcome! It'll be a matter of updating that library, releasing a new version there, and then bumping the version that this repo uses.

**Comment by 0xStarcat** [comment]
closing because issue not related to this repo - see https://github.com/0xStarcat/Moshier-Ephemeris-JS
